version: 2.0
jobs:

  test:
    docker:
    - image: vstromtsova/ca-project_web:latest
    steps:
    - checkout
    - run:
        name: Python Test
        command:
          python tests.py
    - store_test_results:
        path: build/test-results
    - persist_to_workspace:
        root: .
        paths:
          - .


  package:

    docker:
      - image: vstromtsova/ca-project_web:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy Over SSH
          command: |
            ssh -i $SSH_KEY -oStrictHostKeyChecking=no ubuntu@35.187.61.114 "apt-get update -y && apt-get install docker -y && docker-compose up"


workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - package:
          requires:
            - test
  
