version: 2.0
jobs:
  package:
    docker:
      - image: vstromtsova/ca-project_web:latest
    steps:
      - run:
          name: Python
          command: 
            python run.py       

  test: 
    docker:
      - image: vstromtsova/ca-project_web:latest
    steps:
      - run:
          name: Python Test
          command:
            python test.py
      - store_test_results:
          path: build/test-results


workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - package:
          requires:
            - test
  
